services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-next
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env.local
    environment:
      # authSource=admin required when setting database name in URI
      MONGODB_URI: mongodb://root:example@mongo:27017/eventos-rincon?authSource=admin
    depends_on:
      - mongo

volumes:
  mongo-data:
